### ISSUE TITLE
Run failed: Code execution service is unavailable when executing Python code blocks in Dify

### ISSUE THREAD

**Issue by unmo** [langgenius/dify-sandbox#126]
When running Python code blocks in Dify, the following error occurs:

```Run failed: Code execution service is unavailable```

Logs from the sandbox container:

```2025/02/04 10:54:25 setup.go:29: [INFO]initializing nodejs runner environment...
2025/02/04 10:54:25 setup.go:85: [INFO]nodejs runner environment initialized
2025/02/04 10:54:25 setup.go:33: [INFO]initializing python runner environment...
2025/02/04 10:54:25 config.go:129: [INFO]network has been enabled
2025/02/04 10:54:25 config.go:145: [INFO]using https proxy: http://ssrf_proxy:3128
2025/02/04 10:54:25 config.go:154: [INFO]using http proxy: http://ssrf_proxy:3128
2025/02/04 10:54:25 server.go:20: [INFO]config init success
2025/02/04 10:54:25 server.go:26: [INFO]runner dependencies init success
2025/02/04 10:54:25 cocrrent.go:31: [INFO]setting max requests to 50
2025/02/04 10:54:25 server.go:47: [INFO]installing python dependencies...
2025/02/04 10:54:25 server.go:53: [INFO]python dependencies installed
2025/02/04 10:54:25 server.go:55: [INFO]initializing python dependencies sandbox...
2025/02/04 10:54:25 cocrrent.go:13: [INFO]setting max workers to 4
2025/02/04 10:54:56 env.go:30: [WARN]python lib path /usr/lib/python3.10 is not available
2025/02/04 10:54:56 env.go:30: [WARN]python lib path /usr/lib/python3 is not available
[GIN] 2025/02/04 - 10:55:01 | 404 |         753ns |              :: | GET      "/squid-internal-dynamic/netdb"
2025/02/04 10:55:07 env.go:30: [WARN]python lib path /run/systemd/resolve/stub-resolv.conf is not available
2025/02/04 10:55:07 env.go:30: [WARN]python lib path /run/resolvconf/resolv.conf is not available
2025/02/04 10:55:15 server.go:60: [INFO]python dependencies sandbox initialized
```

Notably, [WARN] messages indicate Python library paths that differ from what’s specified in the config.yaml.

```config.yaml
app:
  port: 8194
  debug: True
  key: dify-sandbox
max_workers: 4
max_requests: 50
worker_timeout: 5
python_path: /usr/local/bin/python3
enable_network: True # please make sure there is no network risk in your environment
allowed_syscalls: # please leave it empty if you have no idea how seccomp works
proxy:
  socks5: ''
  http: ''
  https: ''
```

Additionally, the sandbox container status shows as unhealthy, which is concerning.

Environment Details:

Dify Version: 0.15.2 (pulled via git pull from https://github.com/langgenius/dify)
Question:

How can I resolve this issue to successfully execute Python code blocks?
Why is the sandbox container showing as unhealthy, and how can this be fixed?
Is the mismatch in the Python path between the logs and config.yaml causing the issue?
Any guidance would be greatly appreciated.

**Comment by unmo** [comment]
Here's the translation for the GitHub issue:

Resolved:
This issue has been resolved with #3675. Thank you very much!

**Comment by z-x-x136** [comment]
How did you solve it, I saw langgenius/dify#3675, still won't solve it.

sandbox-1     | 2025/02/17 02:22:08 setup.go:85: [INFO]nodejs runner environment initialized
sandbox-1     | 2025/02/17 02:22:08 setup.go:33: [INFO]initializing python runner environment...
sandbox-1     | 2025/02/17 02:22:08 config.go:129: [INFO]network has been enabled
sandbox-1     | 2025/02/17 02:22:08 config.go:145: [INFO]using https proxy: http://ssrf_proxy:3128
sandbox-1     | 2025/02/17 02:22:08 config.go:154: [INFO]using http proxy: http://ssrf_proxy:3128
sandbox-1     | 2025/02/17 02:22:08 server.go:20: [INFO]config init success
sandbox-1     | 2025/02/17 02:22:08 server.go:26: [INFO]runner dependencies init success
sandbox-1     | 2025/02/17 02:22:08 cocrrent.go:31: [INFO]setting max requests to 50
sandbox-1     | 2025/02/17 02:22:08 cocrrent.go:13: [INFO]setting max workers to 4
sandbox-1     | 2025/02/17 02:22:08 server.go:47: [INFO]installing python dependencies...
sandbox-1     | 2025/02/17 02:22:17 setup.go:146: [ERROR]failed to wait for the command to complete
sandbox-1     | 2025/02/17 02:22:17 server.go:51: [PANIC]failed to install python dependencies: exit status 1
sandbox-1     | panic:
sandbox-1     |
sandbox-1     | goroutine 7 [running]:
sandbox-1     | github.com/langgenius/dify-sandbox/internal/utils/log.(*Log).Panic(...)
sandbox-1     |         /home/runner/work/dify-sandbox/dify-sandbox/internal/utils/log/core.go:55
sandbox-1     | github.com/langgenius/dify-sandbox/internal/utils/log.Panic({0x8ff40e?, 0xd?}, {0xc000361fc0?, 0x0?, 0x0?})
sandbox-1     |         /home/runner/work/dify-sandbox/dify-sandbox/internal/utils/log/core.go:209 +0x6f
sandbox-1     | github.com/langgenius/dify-sandbox/internal/server.initDependencies()
sandbox-1     |         /home/runner/work/dify-sandbox/dify-sandbox/internal/server/server.go:51 +0x86
sandbox-1     | created by github.com/langgenius/dify-sandbox/internal/server.Run
sandbox-1     |         /home/runner/work/dify-sandbox/dify-sandbox/internal/server/server.go:97 +0x25
sandbox-1 exited with code 2

**Comment by unmo** [comment]
When docker-api-1 tries to access docker-sandbox-1, the request is forwarded to a proxy node, causing network access issues. Therefore, it's necessary to add sandbox to NO_PROXY, like this:

```
NO_PROXY: 'localhost,127.0.0.1,172.17.*.*, .local, weaviate, sandbox'
```

**Comment by z-x-x136** [comment]
NO_PROXY: 'localhost, 127.0.0.1, 172.17. *. *, the local, weaviate, sandbox' is set in the docker - compose Settings or container

**Comment by unmo** [comment]
The details of the error are slightly different from mine. The cause is unknown.

**Comment by FlypigW** [comment]
![Image](https://github.com/user-attachments/assets/cc043b73-6ee7-47f6-9e3e-5b10164db59f)
一开始我使用如下的config.yaml
app:
  port: 8194
  debug: True

但是出现了以上情况

后来我按照链接更改了config.yaml
app:
  port: 8194
  debug: True
  key: dify-sandbox
max_workers: 4
max_requests: 50
worker_timeout: 5
python_path: /usr/local/bin/python3
enable_network: True # please make sure there is no network risk in your environment
enable_preload: False # please keep it as False for security purposes
allowed_syscalls: # please leave it empty if you have no idea how seccomp works
proxy:
  socks5: ''
  http: ''
  https: ''

然后就成功了

https://github.com/langgenius/dify-sandbox/blob/main/conf/config.yaml
