### ISSUE TITLE
how to change the default time zone

### ISSUE THREAD

**Issue by lordk911** [langgenius/dify-sandbox#50]
when : 
![image](https://github.com/user-attachments/assets/af432ea2-57b5-4a3e-9eb0-a10c40f51309)

it will use the default UTC timezone

when : 
![image](https://github.com/user-attachments/assets/754e732d-b9b8-4df0-8f07-3644d2cbe3d8)

will got error:` operation not permitted`

**Comment by lordk911** [comment]
I deploy dify use k8s helm : https://github.com/douban/charts/tree/master/charts/dify

I've set the sandbox container env:

```
- name: TZ
      value: "Asia/Shanghai"
```

and go into the container:

![image](https://github.com/user-attachments/assets/b7cc5a41-0fe0-465f-bb3d-3f27edd61c59)

But why In dify when exec code in python it still use UTC timezone

**Comment by lordk911** [comment]
1、go into the containser anf exec : `ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime` , can work it out

**Comment by Yeuoly** [comment]
Thanks so much for reporting this, I have fixed it.

**Comment by sknightq** [comment]
@Yeuoly I set the TZ environment in dockerfile，but still not work.
In dockerfile
```
# 设置时区为上海
ENV TZ=Asia/Shanghai

RUN rm -rf /var/lib/apt/lists/* \
    && chmod +x /main \
    && chmod +x /env \
    && pip3 install jinja2 requests httpx PySocks httpx[socks] \
    && wget -O /opt/node-v20.11.1-linux-x64.tar.xz https://npmmirror.com/mirrors/node/v20.11.1/node-v20.11.1-linux-x64.tar.xz \
    && tar -xvf /opt/node-v20.11.1-linux-x64.tar.xz -C /opt \
    && ln -s /opt/node-v20.11.1-linux-x64/bin/node /usr/local/bin/node \
    && rm -f /opt/node-v20.11.1-linux-x64.tar.xz \
    && /env \
    && rm -f /env \
    && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo Asia/Shanghai > /etc/timezone \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*
```
My Code Request:
```
// request
{
    "language":"nodejs",
    "code":"console.log(new Date('2024-10-03 15:26:49').getTime())"
}
// response
{
    "code": 200,
    "message": "success",
    "data": {
        "error": "",
        "stdout": "1727969209000\n"
    }
}
// console.log(new Date(1727969209000)) // Thu Oct 03 2024 23:26:49 GMT+0800 (China Standard Time) 
```
